#-*- coding: utf-8 -*-

KEY_GOOGLE_OAUTH_TOKEN = 'google-access-token'
KEY_TWITTER_OAUTH_TOKEN = 'twitter-access-token'
KEY_GITHUB_OAUTH_TOKEN = 'github-access-token'

KEY_OAUTH_TOKEN_LIST = [
    KEY_GOOGLE_OAUTH_TOKEN,
    KEY_TWITTER_OAUTH_TOKEN,
    KEY_GITHUB_OAUTH_TOKEN,
    ]

PROVIDER_TWITTER = 'twitter'
PROVIDER_GITHUB = 'github'
PROVIDER_GOOGLE = 'google'
PROVIDER_LIST = [
    PROVIDER_TWITTER,
    PROVIDER_GITHUB,
    PROVIDER_GOOGLE,
    ]
